/*******************************************************************************
*                                                                              *
* FILE:                                                                        *
* 		init.h                                                                 *
*                                                                              *
* DESCRIPTION:                                                                 *
* 		Contains initialization routines for MCU core and peripherals          *
*                                                                              *
* COPYRIGHT:                                                                   *
*       Copyright (c) 2025 Sun Devil Rocketry & (c) 2022 STMicroelectronics.   *
*       All rights reserved.                                                   *
*                                                                              *
*       This software is licensed under terms that can be found in the LICENSE *
*       file in the root directory of this software component.                 *
*       If no LICENSE file comes with this software, it is covered under the   *
*       BSD-3-Clause.                                                          *
*                                                                              *
*       https://opensource.org/license/bsd-3-clause                            *
*																			   *
*		Due to the use of autogenerated code in this file that is licensed by  *
*		STMicroelectronics, that entity is granted unrestricted rights to the  *
*		source code in this file. Sun Devil Rocketry does not claim ownership  *
*		of any of STMicroelectronics's intellectual property, nor do we claim  *
*		to have any support or endorsement from STMicroelectronics beyond      *
*		using their source code in accordance with their license agreement.    *
*                                                                              *
*******************************************************************************/


/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef INIT_H 
#define INIT_H

#ifdef __cplusplus
extern "C" {
#endif


/*------------------------------------------------------------------------------
 Standard Includes                                                              
------------------------------------------------------------------------------*/


/*------------------------------------------------------------------------------
 Project Includes                                                               
------------------------------------------------------------------------------*/
#include "main.h"

/*------------------------------------------------------------------------------
 Macros and Constants
------------------------------------------------------------------------------*/
#define SERVO_PRESCALER 1920
#define SERVO_PERIOD    1000

/*------------------------------------------------------------------------------
 Function prototypes                                                          
------------------------------------------------------------------------------*/
void SystemClock_Config      ( void );      /* clock configuration            */
void PeriphCommonClock_Config( void );      /* Common clock configuration     */
void CRYP_Init               ( void );      /* Crypto configuration           */
void GPIO_Init               ( void );      /* GPIO configurations            */
void USB_UART_Init           ( void );      /* USB UART configuration         */
void GPS_UART_Init           ( void );      /* GPS UART configuration         */
void Baro_I2C_Init           ( void );      /* Baro sensor I2C configuration  */
void IMU_GPS_I2C_Init        ( void );      /* IMU/GPS I2C configuration      */
void FLASH_SPI_Init          ( void );      /* FLASH SPI configuration        */
void BUZZER_TIM_Init         ( void );      /* Buzzer Timer configuration     */
void SD_SDMMC_Init           ( void );      /* SD Card SDMMC Interface        */
void PWM4_TIM_Init           ( void );      /* Motor 4 PWM configuration      */
void PWM123_TIM_Init         ( void );      /* Motor 1,2,3 PWM configuration  */


#ifdef __cplusplus
}
#endif
#endif /* INIT_H */
/*******************************************************************************
* END OF FILE                                                                  * 
*******************************************************************************/