/*******************************************************************************
*                                                                              *
* FILE:                                                                        *
*       stm32h7xx_it.c                                                         *
*                                                                              *
* DESCRIPTION:                                                                 *
*       Contains implementation of interrupt service routines                  *
*                                                                              *
* COPYRIGHT:                                                                   *
*       Copyright (c) 2025 Sun Devil Rocketry & (c) 2022 STMicroelectronics.   *
*       All rights reserved.                                                   *
*                                                                              *
*       This software is licensed under terms that can be found in the LICENSE *
*       file in the root directory of this software component.                 *
*       If no LICENSE file comes with this software, it is covered under the   *
*       BSD-3-Clause.                                                          *
*                                                                              *
*       https://opensource.org/license/bsd-3-clause                            *
*																			                                         *
*		    Due to the use of autogenerated code in this file that is licensed by  *
*		    STMicroelectronics, that entity is granted unrestricted rights to the  *
*		    source code in this file. Sun Devil Rocketry does not claim ownership  *
*		    of any of STMicroelectronics's intellectual property, nor do we claim  *
*		    to have any support or endorsement from STMicroelectronics beyond      *
*		    using their source code in accordance with their license agreement.    *
*                                                                              *
*******************************************************************************/


/*------------------------------------------------------------------------------
Standard Includes                                                                     
------------------------------------------------------------------------------*/
#include "main.h"
#include "sdr_pin_defines_A0002.h"
#include "stm32h7xx_it.h"
#include "gps.h"
#include "usb.h"
#include "imu.h"
#include "baro.h"
#include "timer.h"
#include "lora.h"
#include "error_sdr.h"
#include <string.h>

/*------------------------------------------------------------------------------
External variables                                                                     
------------------------------------------------------------------------------*/
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim5;
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c2;
extern DMA_HandleTypeDef hdma_spi4_rx;
extern DMA_HandleTypeDef hdma_spi4_tx;
extern SPI_HandleTypeDef hspi4;
extern UART_HandleTypeDef huart4;

/*------------------------------------------------------------------------------
             Cortex Processor Interruption and Exception Handlers             
------------------------------------------------------------------------------*/
extern uint8_t            gps_mesg_byte;
extern uint8_t            rx_buffer[GPSBUFSIZE];
extern uint8_t            rx_index;
extern GPS_DATA           gps_data;
/**
  * @brief This function handles Non maskable interrupt.
  */
void NMI_Handler(void)
{
  while (1)
  {
  }
}

/**
  * @brief This function handles Hard fault interrupt.
  */
void HardFault_Handler(void)
{
  while (1)
  {
  }
}

/**
  * @brief This function handles Memory management fault.
  */
void MemManage_Handler(void)
{
  while (1)
  {
  }
}

/**
  * @brief This function handles Pre-fetch fault, memory access fault.
  */
void BusFault_Handler(void)
{
  while (1)
  {
  }
}

/**
  * @brief This function handles Undefined instruction or illegal state.
  */
void UsageFault_Handler(void)
{
  while (1)
  {
  }
}

/**
  * @brief This function handles System service call via SWI instruction.
  */
void SVC_Handler(void)
{
}

/**
  * @brief This function handles Debug monitor.
  */
void DebugMon_Handler(void)
{
}

/**
  * @brief This function handles Pendable request for system service.
  */
void PendSV_Handler(void)
{
}

/**
  * @brief This function handles System tick timer.
  */
void SysTick_Handler(void)
{
  HAL_IncTick();
}


/******************************************************************************/
/* STM32H7xx Peripheral Interrupt Handlers                                    */
/* Add here the Interrupt Handlers for the used peripherals.                  */
/* For the available peripheral interrupt handler names,                      */
/* please refer to the startup file (startup_stm32h7xx.s).                    */
/******************************************************************************/


/**
  * @brief This function handles I2C1 event interrupt. (BARO)
  */
void I2C1_EV_IRQHandler(void)
{
  /* USER CODE BEGIN I2C1_EV_IRQn 0 */

  /* USER CODE END I2C1_EV_IRQn 0 */
  HAL_I2C_EV_IRQHandler(&hi2c1);
  /* USER CODE BEGIN I2C1_EV_IRQn 1 */

  /* USER CODE END I2C1_EV_IRQn 1 */
}

/**
  * @brief This function handles I2C1 error interrupt. (BARO)
  */
void I2C1_ER_IRQHandler(void)
{
  HAL_I2C_ER_IRQHandler(&hi2c1);
}


/**
  * @brief This function handles I2C2 event interrupt. (IMU)
  */
void I2C2_EV_IRQHandler(void)
{
  /* USER CODE BEGIN I2C2_EV_IRQn 0 */

  /* USER CODE END I2C2_EV_IRQn 0 */
  HAL_I2C_EV_IRQHandler(&hi2c2);
  /* USER CODE BEGIN I2C2_EV_IRQn 1 */

  /* USER CODE END I2C2_EV_IRQn 1 */
}


/**
  * @brief This function handles I2C2 error interrupt. (IMU)
  */
void I2C2_ER_IRQHandler(void)
{
  HAL_I2C_ER_IRQHandler(&hi2c2);
}


/**
  * @brief This function handles SPI4 global interrupt.
  */
void SPI4_IRQHandler(void)
{
  /* USER CODE BEGIN SPI4_IRQn 0 */

  /* USER CODE END SPI4_IRQn 0 */
  HAL_SPI_IRQHandler(&hspi4);
  /* USER CODE BEGIN SPI4_IRQn 1 */

  /* USER CODE END SPI4_IRQn 1 */
}


/**
  * @brief This function handles TIM2 global interrupt.
  */
void TIM2_IRQHandler(void)
{
  /* USER CODE BEGIN TIM2_IRQn 0 */

  /* USER CODE END TIM2_IRQn 0 */
  HAL_TIM_IRQHandler(&htim2);
  /* USER CODE BEGIN TIM2_IRQn 1 */

  /* USER CODE END TIM2_IRQn 1 */
}


/**
  * @brief This function handles TIM3 global interrupt.
  */
void TIM3_IRQHandler(void)
{
  /* USER CODE BEGIN TIM3_IRQn 0 */

  /* USER CODE END TIM3_IRQn 0 */
  HAL_TIM_IRQHandler(&htim3);
  /* USER CODE BEGIN TIM3_IRQn 1 */

  /* USER CODE END TIM3_IRQn 1 */
}


/**
  * @brief This function handles TIM5 global interrupt.
  */
void TIM5_IRQHandler(void)
{
  /* USER CODE BEGIN TIM5_IRQn 0 */

  /* USER CODE END TIM5_IRQn 0 */
  HAL_TIM_IRQHandler(&htim5);
  /* USER CODE BEGIN TIM5_IRQn 1 */

  /* USER CODE END TIM5_IRQn 1 */
}


void UART4_IRQHandler(void)
{
   /* USER CODE BEGIN UART4_IRQn 0 */

  /* USER CODE END UART4_IRQn 0 */
  HAL_UART_IRQHandler(&huart4);
  /* USER CODE BEGIN UART4_IRQn 1 */


  if (gps_mesg_byte != '\n' && rx_index < sizeof(rx_buffer)) {
  		rx_buffer[rx_index++] = gps_mesg_byte;
	} else {
      if(gps_mesg_validate((char*) rx_buffer))
        GPS_parse(&gps_data, (char*) rx_buffer);
      rx_index = 0;
      memset(rx_buffer, 0, sizeof(rx_buffer));
	}
  gps_receive_IT(&gps_mesg_byte, 1);
	// usb_transmit(&gps_data, 1, 5);

  /* USER CODE END UART4_IRQn 1 */
}


void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
if ( htim->Instance == TIM5 )
  {
  micro_tim_IT_handler();
  }
} /* HAL_TIM_PeriodElapsedCallback */


void HAL_I2C_MemRxCpltCallback(I2C_HandleTypeDef *hi2c) {
  if( hi2c == &( BARO_I2C ) )
    {
    /* baro */
    baro_IT_handler();
    }
  else if( hi2c == &( IMU_I2C ) )
    {
    /* imu */
    imu_it_handler();
    }
}


void HAL_I2C_ErrorCallback( I2C_HandleTypeDef *hi2c )
    {
    volatile uint32_t error = HAL_I2C_GetError( hi2c );
    (void)error; /* debug mode won't optimize this code away */
    if ( hi2c == &( BARO_I2C ) )
        {
        #ifdef DEBUG
        error_fail_fast( ERROR_BARO_I2C_ERROR );
        #endif
        }
    else if ( hi2c == &( IMU_I2C ) )
        {
        #ifdef DEBUG
        error_fail_fast( ERROR_IMU_I2C_ERROR );
        #endif
        }
    }


/**
  * @brief  This function handles DMA1 Stream0 global interrupt (SPI4/LORA_SPI RX).
  */
void DMA1_Stream0_IRQHandler(void)
{
  HAL_DMA_IRQHandler(&hdma_spi4_rx);
}

/**
  * @brief  This function handles DMA1 Stream1 global interrupt (SPI4/LORA_SPI TX).
  */
void DMA1_Stream1_IRQHandler(void)
{
  HAL_DMA_IRQHandler(&hdma_spi4_tx);
}

/**
  * @brief  SPI DMA transmit-complete callback (TX path: lora_transmit_async).
  */
void HAL_SPI_TxCpltCallback( SPI_HandleTypeDef *hspi )
{
  if ( hspi == &( LORA_SPI ) )
    {
    lora_process_async_cb();
    }
}

/**
  * @brief  SPI DMA full-duplex transmit/receive-complete callback
  *         (RX path: lora_request_receive_async, full-duplex dummy-TX read).
  */
void HAL_SPI_TxRxCpltCallback( SPI_HandleTypeDef *hspi )
{
  if ( hspi == &( LORA_SPI ) )
    {
    lora_process_async_cb();
    }
}

/**
  * @brief  SPI DMA error callback (both TX and RX paths route here).
  */
void HAL_SPI_ErrorCallback( SPI_HandleTypeDef *hspi )
{
  if ( hspi == &( LORA_SPI ) )
    {
    lora_process_async_error_cb();
    }
}

/**
  * @brief  DIO0 (RxDone/TxDone) EXTI dispatch. LORA_IO0_PIN = GPIO_PIN_8
  *         (GPIOE) -> shared EXTI9_5_IRQn.
  */
void EXTI9_5_IRQHandler( void )
{
  HAL_GPIO_EXTI_IRQHandler( LORA_IO0_PIN );
}

/**
  * @brief  GPIO EXTI callback - fires lora_process_dio0_cb() on every
  *         DIO0 edge, which internally dispatches to TxDone or RxDone
  *         handling depending on current chip state.
  */
void HAL_GPIO_EXTI_Callback( uint16_t GPIO_Pin )
{
  if ( GPIO_Pin == LORA_IO0_PIN )
    {
    lora_process_dio0_cb();
    }
}

/*******************************************************************************
* END OF FILE                                                                  * 
*******************************************************************************/
