name: FCF Stability Check
run-name: ${{ github.actor }} is verifying build stability 🚀
on: 
  pull_request:
  push:
    branches:
      - main
      - development/**
      - personal/ES/**
      - integration/**
permissions:
  contents: read
jobs:
  Check-build-stability:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }}."
      - name: Check out dependencies
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.3.Rel1' # <-- The compiler release to use
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build APPA application (with debug flag)
        run: |    
          cd app/rev2
          make clean
          make
      - name: Build APPA application (with release flag)
        run: |
          cd app/rev2
          make clean
          make DEBUG=0
      - name: Build emulator (Linux version)
        run: |
          cd app/rev2
          make clean
          make emulator
      - run: echo "🍏 This job's status is ${{ job.status }}."